export const metadata = {
	title: "Стрекоза - детский игровой центр",
	description: "Generated by create next app",
};

const Home = () => {
	return (
		<main>
			<div>Page</div>
		</main>
	);
}

export default Home;